### ISSUE TITLE
Better error log when Redis down

### ISSUE THREAD

**Issue by dejlek** [quantmind/pulsar-queue#7]
Here is what I get when I run the queue with Redis down:

```
15:13:29 [p=3196, t=140273372366592, CRITICAL, pulsar.tasks] Stopping
Traceback (most recent call last):
  File "/home/dejan/.local/lib/python3.4/site-packages/pulsar/apps/__init__.py", line 127, in monitor_start
    yield from coro
  File "/usr/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "/home/dejan/.local/lib/python3.4/site-packages/pulsar/apps/data/redis/pubsub.py", line 91, in _subscribe
    self._connection = yield from self.store.connect(protocol_factory)
  File "/home/dejan/.local/lib/python3.4/site-packages/pulsar/apps/data/redis/store.py", line 102, in connect
    protocol_factory, host, port)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 625, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.4/asyncio/base_events.py", line 612, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 438, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6379)
```

I believe it would be much better if we get a clear error message saying something like `Critical error, Redis is not up and running." or even better `Critical error! TASK_BACKEND is not accessible!`

Perhaps a good idea is to show this message, and then retry to connect to the backend again using some re-try strategy. Reason why this is good is that in the case we are restarting the backend for some reason, queue will start working soon after the backend is up.

**Comment by lsbardel** [comment]
Indeed, but this is covered by #2 too.
